log:
  level: DEBUG
  console_output: true
app:
  debug: true
listen:
  port: 9999

images:
  base_service_url: https://falokut.ru/api/images-storage-service
  base_image_path: https://falokut.ru/image
db:
  schema: dish_as_a_service
  host: localhost
  port: 5432
  database: postgres
tg_bot:
  debug: true
  timeout: 100
payment:
  expiration_delay: 30m
