basePath: /api/dish_as_a_service
definitions:
  domain.AddCategoryRequest:
    properties:
      name:
        minLength: 1
        type: string
    required:
    - name
    type: object
  domain.AddDishRequest:
    properties:
      categories:
        items:
          type: integer
        type: array
      description:
        maxLength: 256
        type: string
      image:
        items:
          type: integer
        type: array
      name:
        minLength: 1
        type: string
      price:
        minimum: 800
        type: integer
    required:
    - name
    type: object
  domain.DeleteCategoryRequest:
    properties:
      id:
        type: integer
    type: object
  domain.Dish:
    properties:
      categories:
        items:
          type: string
        type: array
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
      url:
        type: string
    type: object
  domain.DishCategory:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  domain.Empty:
    type: object
  domain.GetDishesCategory:
    properties:
      id:
        type: integer
    type: object
  domain.GetUserIdByTelegramIdResponse:
    properties:
      userId:
        type: string
    type: object
  domain.IsUserAdminRequest:
    properties:
      userId:
        type: string
    required:
    - userId
    type: object
  domain.IsUserAdminResponse:
    properties:
      isAdmin:
        type: boolean
    type: object
  domain.OrderItem:
    properties:
      count:
        type: integer
      dishId:
        type: integer
      name:
        type: string
      price:
        type: integer
      status:
        type: string
      totalPrice:
        type: integer
    type: object
  domain.ProcessOrderRequest:
    properties:
      items:
        additionalProperties:
          type: integer
        type: object
      paymentMethod:
        minLength: 1
        type: string
      userId:
        type: string
      wishes:
        type: string
    required:
    - items
    - paymentMethod
    - userId
    type: object
  domain.ProcessOrderResponse:
    properties:
      paymentUrl:
        description: for some payment methods may be empty
        type: string
    type: object
  domain.RenameCategoryRequest:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
    - id
    - name
    type: object
  domain.UserOrder:
    properties:
      createdAt:
        type: string
      id:
        type: string
      items:
        items:
          $ref: '#/definitions/domain.OrderItem'
        type: array
      paymentMethod:
        type: string
      status:
        type: string
      total:
        type: integer
      wishes:
        type: string
    type: object
  github_com_Falokut_go-kit_http_apierrors.Error:
    properties:
      details:
        additionalProperties: {}
        type: object
      errorCode:
        type: integer
      errorMessage:
        type: string
    type: object
info:
  contact: {}
  description: Сервис для заказа еды
  title: falokut_dish_as_a_service
  version: 1.0.0
paths:
  /dishes:
    get:
      description: возвращает список блюд
      parameters:
      - description: список идентификаторов блюд через запятую
        in: query
        name: ids
        type: string
      - description: список идентификаторов категорий через запятую
        in: query
        name: сategories
        type: string
      - description: максимальное количество блюд
        in: query
        name: limit
        type: integer
      - description: смещение
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Dish'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
      summary: dish
      tags:
      - dishes
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.AddDishRequest'
      - description: id пользователя
        in: header
        name: X-USER-ID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Empty'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
      summary: Add Dish
      tags:
      - dishes
  /dishes/all_categories:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.DishCategory'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
      summary: Получить категории
      tags:
      - dishes_categories
  /dishes/categories:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.DishCategory'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
      summary: Получить категории
      tags:
      - dishes_categories
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.AddCategoryRequest'
      - description: id пользователя
        in: header
        name: X-USER-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.DishCategory'
        "400":
          description: Bad Request
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
      summary: Создать категорию
      tags:
      - dishes_categories
  /dishes/categories/:id:
    delete:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.DeleteCategoryRequest'
      - description: id пользователя
        in: header
        name: X-USER-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/domain.Empty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
      summary: Удалить категорию
      tags:
      - dishes_categories
    get:
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.GetDishesCategory'
      - description: Идентификатор категории
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.DishCategory'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
      summary: Получить категорию
      tags:
      - dishes_categories
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.RenameCategoryRequest'
      - description: id пользователя
        in: header
        name: X-USER-ID
        required: true
        type: string
      - description: Идентификатор категории
        in: path
        name: id
        required: true
        type: integer
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.RenameCategoryRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/domain.Empty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
      summary: Переименовать категорию
      tags:
      - dishes_categories
  /dishes/delete/:id:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id пользователя
        in: header
        name: X-USER-ID
        required: true
        type: string
      - description: идентификатор блюда
        in: query
        name: id
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Empty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
      summary: Delete Dish
      tags:
      - dishes
  /dishes/edit/:id:
    post:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Empty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
  /orders:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.ProcessOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.ProcessOrderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
      summary: Заказать
      tags:
      - order
  /orders/my:
    get:
      parameters:
      - description: максимальное количество блюд
        in: query
        name: limit
        type: integer
      - description: смещение
        in: query
        name: offset
        type: integer
      - description: id пользователя
        in: header
        name: X-USER-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.UserOrder'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
      summary: Получить заказы
      tags:
      - order
  /users/get_by_telegram_id/:telegramId:
    get:
      consumes:
      - application/json
      parameters:
      - description: Идентификатор категории
        in: path
        name: telegramId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.GetUserIdByTelegramIdResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
      summary: Получить id пользователя по telegram id
      tags:
      - users
  /users/is_admin:
    get:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.IsUserAdminRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.IsUserAdminResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Falokut_go-kit_http_apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Проверить, является ли пользователь админом
      tags:
      - users
swagger: "2.0"
