log:
  level: DEBUG
  console_output: true
app:
  admin_secret: secret
listen:
  port: 8080

images:
  base_service_url: http://gateway:3000/api/images-storage-service
  base_image_path: https://falokut.ru/image
db:
  schema: dish_as_a_service
  host: postgres
  port: 5432
  database: postgres
  username: postgres
  passport: postgres
tg_bot:
  timeout: 10
  limit: 10
payment:
  expiration_delay: 30m
